# Generated by Django 4.0.3 on 2022-03-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='retal_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
